services:
  - type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn shop.wsgi:application
      "
